### ISSUE TITLE
국회의원 예비후보자 정보 사이트 추가

### ISSUE THREAD

**Issue by rest515** [parti-coop/awesome-democracy-apps#1]
아래 사이트를 추가하면 좋겠습니다. 
http://cpmadang.org/?q=candi-list&field_vote_zone_tid=_none&field_party_tid=_none

**Comment by mozodev** [comment]
안 그래도 얼마전 링크 수집해봤습니다.
https://parti-xyz.hackpad.com/better-cosmos--V0YfncgtlgK
여기 있는 걸 다 올려보겠습니다.
