### ISSUE TITLE
도메인 구입

### ISSUE THREAD

**Issue by rest515** [parti-coop/awesome-democracy-apps#3]
http://awesome-democracy-apps.net 도메인을 구입해서 클라우드플레어에 연결합니다.

**Comment by dalikim** [comment]
좋습니다. :+1:

**Comment by mozodev** [comment]
+1 프로젝트 깃헙 페이지 브랜치라 경로 수정이 필요할 수도 있겠네요

**Comment by rest515** [comment]
http://awesome-democracy-apps.xyz 구매하였습니다. 클라우드플레어에 연결하고 공유하겠습니다.

**Comment by rest515** [comment]
클라우드플레어에 dns 연결했습니다.

**Comment by mozodev** [comment]
http://awesome-democracy-apps.xyz
